import { describe, it, expect } from 'vitest';
import { classifyPath, categoryToBucket } from './linguist-classifier.ts';

function bucket(p: string) { return categoryToBucket(classifyPath(p)); }

describe('classifyPath → bucket (TRASH/DOCS/INTERESTING/UNCLEAR)', () => {
  // ── TRASH: autogenerated / vendored ──────────────────────────────
  it('Visual Studio designer files → TRASH', () => {
    expect(bucket('client/Forms/MainForm.Designer.cs')).toBe('TRASH');
    expect(bucket('src/Resources.Designer.cs')).toBe('TRASH');
  });

  it('lock files → TRASH', () => {
    expect(bucket('package-lock.json')).toBe('TRASH');
    expect(bucket('yarn.lock')).toBe('TRASH');
    expect(bucket('Cargo.lock')).toBe('TRASH');
    expect(bucket('poetry.lock')).toBe('TRASH');
    expect(bucket('composer.lock')).toBe('TRASH');
  });

  it('IDE config → TRASH', () => {
    expect(bucket('.idea/workspace.xml')).toBe('TRASH');
  });

  it('node_modules → TRASH', () => {
    expect(bucket('node_modules/react/index.js')).toBe('TRASH');
  });

  it('dist/ and vendor/ → TRASH', () => {
    expect(bucket('dist/bundle.js')).toBe('TRASH');
    expect(bucket('client/vendor/jquery.js')).toBe('TRASH');
  });

  it('minified JS/CSS → TRASH', () => {
    expect(bucket('static/app.min.js')).toBe('TRASH');
    expect(bucket('styles/bootstrap.min.css')).toBe('TRASH');
  });

  // ── DOCS ──────────────────────────────────────────────────────────
  it('README and CHANGELOG → DOCS', () => {
    expect(bucket('README.md')).toBe('DOCS');
    expect(bucket('CHANGELOG.md')).toBe('DOCS');
    expect(bucket('LICENSE')).toBe('DOCS');
  });

  it('docs/ and examples/ → DOCS', () => {
    expect(bucket('docs/intro.md')).toBe('DOCS');
    expect(bucket('examples/basic.py')).toBe('DOCS');
  });

  // ── INTERESTING: known source extensions ─────────────────────────
  it('common source extensions → INTERESTING', () => {
    expect(bucket('src/main.ts')).toBe('INTERESTING');
    expect(bucket('src/main.py')).toBe('INTERESTING');
    expect(bucket('src/main.go')).toBe('INTERESTING');
    expect(bucket('src/main.rs')).toBe('INTERESTING');
    expect(bucket('src/main.cs')).toBe('INTERESTING');
    expect(bucket('src/main.java')).toBe('INTERESTING');
  });

  // ── UNCLEAR: unknown extensions ──────────────────────────────────
  it('unknown extensions → UNCLEAR', () => {
    expect(bucket('some/weird/file.xyz123')).toBe('UNCLEAR');
  });

  it('raw category is returned (not just bucket)', () => {
    // Smoke test: the raw classification is still available for debugging
    const cat = classifyPath('README.md');
    expect(['documentation', 'prose']).toContain(cat);
  });
});

describe('categoryToBucket', () => {
  it('maps generated/vendored to TRASH', () => {
    expect(categoryToBucket('generated')).toBe('TRASH');
    expect(categoryToBucket('vendored')).toBe('TRASH');
  });

  it('maps documentation/prose to DOCS', () => {
    expect(categoryToBucket('documentation')).toBe('DOCS');
    expect(categoryToBucket('prose')).toBe('DOCS');
  });

  it('maps programming to INTERESTING', () => {
    expect(categoryToBucket('programming')).toBe('INTERESTING');
  });

  it('maps data/markup/null to UNCLEAR', () => {
    expect(categoryToBucket('data')).toBe('UNCLEAR');
    expect(categoryToBucket('markup')).toBe('UNCLEAR');
    expect(categoryToBucket(null)).toBe('UNCLEAR');
  });
});
