import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import yaml from 'js-yaml';

// ESM shim for CommonJS require — used to resolve linguist-js package directory
const require = createRequire(import.meta.url);

/**
 * Pre-classification categories derived from github-linguist data files.
 *
 * Combines three inputs:
 *   - generated.rb      — paths/files that are autogenerated (protobuf, Designer.cs, etc.)
 *   - vendor.yml        — vendored/third-party code (node_modules, *.d.ts, min.js, ...)
 *   - documentation.yml — human-readable docs (README, CHANGELOG, docs/, ...)
 *   - languages.yml     — extension → language + type (programming/data/markup/prose)
 */
export type LinguistCategory = 'generated' | 'vendored' | 'documentation' | 'programming' | 'data' | 'markup' | 'prose' | null;

interface LanguagesYml {
  [name: string]: {
    type?: string;
    extensions?: string[];
    filenames?: string[];
  };
}

interface LinguistData {
  generated: RegExp[];
  vendored: RegExp[];
  documentation: RegExp[];
  /** Map from lowercased extension (including leading dot) to linguist type */
  extToType: Map<string, string>;
  /** Map from exact filename (e.g. "Dockerfile") to type */
  filenameToType: Map<string, string>;
}

let cached: LinguistData | null = null;

/**
 * Resolve the directory containing the bundled linguist data files.
 *
 * We piggyback on the linguist-js npm package which bundles `ext/generated.rb`,
 * `ext/vendor.yml`, `ext/documentation.yml`, and `ext/languages.yml`. That package
 * is a regular `dependencies` entry so the files are present in the runner image
 * under `/app/node_modules/linguist-js/ext/`.
 *
 * Resolution priority:
 *   1. LINGUIST_DATA_DIR env var (tests)
 *   2. require.resolve('linguist-js') → sibling ext/ directory
 *   3. node_modules/linguist-js/ext relative to cwd (fallback)
 */
function resolveDataDir(): string {
  const envOverride = process.env.LINGUIST_DATA_DIR;
  if (envOverride) return envOverride;

  // Resolve the linguist-js package directory via its package.json and append /ext
  try {
    const pkgJson = require.resolve('linguist-js/package.json');
    const extDir = path.join(path.dirname(pkgJson), 'ext');
    if (fs.existsSync(path.join(extDir, 'languages.yml'))) return extDir;
  } catch {
    // fall through to heuristic fallbacks
  }

  const fallbacks = [
    path.resolve(process.cwd(), 'node_modules/linguist-js/ext'),
    path.resolve(process.cwd(), 'api/node_modules/linguist-js/ext'),
    '/app/node_modules/linguist-js/ext',
  ];
  for (const c of fallbacks) {
    if (fs.existsSync(path.join(c, 'languages.yml'))) return c;
  }
  throw new Error(`linguist-js data directory not found (ext/languages.yml). Is linguist-js installed?`);
}

/**
 * Compile a Ruby/PCRE-ish regex string to a JS RegExp.
 *
 * Most patterns in vendor.yml/documentation.yml/generated.rb use a subset of regex
 * compatible with both engines. We compile with the `i` flag because linguist
 * assumes lowercase filenames on Linux, but real-world files like
 * `MainForm.Designer.cs` (Visual Studio) use mixed case. Case-insensitive
 * matching catches the intent without maintaining parallel case variants.
 *
 * Returns null if the pattern fails to compile.
 */
function compilePattern(pat: string): RegExp | null {
  try {
    return new RegExp(pat, 'i');
  } catch {
    return null;
  }
}

/**
 * Extra TRASH patterns that linguist either omits or classifies as data.
 * These are stable, high-confidence trash files seen in real-world repos.
 */
const EXTRA_TRASH_PATTERNS: RegExp[] = [
  /(^|\/)yarn\.lock$/i,           // linguist has it as YAML data, but it's clearly autogen
  /(^|\/)bun\.lockb?$/i,          // Bun runtime
  /(^|\/)\.bundle-buildinfo\.txt$/i,
  /(^|\/)obj\//i,                 // .NET build output
  /(^|\/)bin\/(Debug|Release)/i,  // .NET build output (without breaking all /bin/ paths)
  /\.AssemblyInfo\.cs$/i,          // .NET autogen
  /\.GlobalUsings\.g\.cs$/i,       // .NET source generators
  /\.razor\.g\.cs$/i,              // Blazor autogen
  /\.feature\.cs$/i,               // SpecFlow
];

/** Parse a YAML-like array of regex strings (one per line after "- "). */
function loadPatternList(filePath: string): RegExp[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const patterns: RegExp[] = [];
  for (const line of lines) {
    const match = /^-\s*(.+?)\s*$/.exec(line);
    if (!match) continue;
    const raw = match[1];
    // Strip trailing comments (rare in these files)
    const re = compilePattern(raw);
    if (re) patterns.push(re);
  }
  return patterns;
}

function loadLanguages(filePath: string): { extToType: Map<string, string>; filenameToType: Map<string, string> } {
  const content = fs.readFileSync(filePath, 'utf-8');
  const parsed = yaml.load(content) as LanguagesYml;
  const extToType = new Map<string, string>();
  const filenameToType = new Map<string, string>();

  for (const [, def] of Object.entries(parsed)) {
    const type = def.type;
    if (!type) continue;
    if (def.extensions) {
      for (const ext of def.extensions) {
        const key = ext.toLowerCase();
        // First-seen wins (language order in YAML is alphabetical; later overrides fine for our coarse
        // "programming vs data vs markup vs prose" goal).
        if (!extToType.has(key)) extToType.set(key, type);
      }
    }
    if (def.filenames) {
      for (const fn of def.filenames) {
        if (!filenameToType.has(fn)) filenameToType.set(fn, type);
      }
    }
  }

  return { extToType, filenameToType };
}

function loadData(): LinguistData {
  if (cached) return cached;
  const dir = resolveDataDir();
  const generated = loadPatternList(path.join(dir, 'generated.rb'));
  const vendored = loadPatternList(path.join(dir, 'vendor.yml'));
  const documentation = loadPatternList(path.join(dir, 'documentation.yml'));
  const { extToType, filenameToType } = loadLanguages(path.join(dir, 'languages.yml'));

  cached = { generated, vendored, documentation, extToType, filenameToType };
  return cached;
}

/** Find the first regex in `patterns` that matches `path` — returns true if any match. */
function matchesAny(filePath: string, patterns: RegExp[]): boolean {
  for (const re of patterns) {
    if (re.test(filePath)) return true;
  }
  return false;
}

/**
 * Classify a file path against linguist data files.
 *
 * Returns:
 *   'generated'     — autogenerated code (treat as TRASH)
 *   'vendored'      — third-party / vendored (treat as TRASH)
 *   'documentation' — README, CHANGELOG, docs/ (treat as DOCS)
 *   'prose'         — Markdown / human-readable text (treat as DOCS)
 *   'programming'   — real source code (treat as INTERESTING, Scout still verifies)
 *   'data'          — JSON / YAML / CSV (treat as UNCLEAR — Scout decides)
 *   'markup'        — HTML / XML / template (treat as UNCLEAR — Scout decides)
 *   null            — unknown extension, Scout must classify
 */
export function classifyPath(filePath: string): LinguistCategory {
  const data = loadData();

  // Pattern-based checks (order matters: generated wins over vendored if both match)
  if (matchesAny(filePath, data.generated)) return 'generated';
  if (matchesAny(filePath, EXTRA_TRASH_PATTERNS)) return 'generated';
  if (matchesAny(filePath, data.vendored)) return 'vendored';
  if (matchesAny(filePath, data.documentation)) return 'documentation';

  // Extension-based lookup from languages.yml
  const basename = filePath.split('/').pop() || filePath;
  const filenameType = data.filenameToType.get(basename);
  if (filenameType) return filenameType as LinguistCategory;

  const dotIdx = basename.lastIndexOf('.');
  if (dotIdx >= 0) {
    const ext = basename.slice(dotIdx).toLowerCase();
    const type = data.extToType.get(ext);
    if (type) return type as LinguistCategory;
  }

  return null;
}

/** Human-readable bucket: where does this classification go in our pipeline? */
export type ScanCategory = 'TRASH' | 'DOCS' | 'INTERESTING' | 'UNCLEAR';

export function categoryToBucket(cat: LinguistCategory): ScanCategory {
  switch (cat) {
    case 'generated':
    case 'vendored':
      return 'TRASH';
    case 'documentation':
    case 'prose':
      return 'DOCS';
    case 'programming':
      return 'INTERESTING';
    case 'data':
    case 'markup':
    case null:
    default:
      return 'UNCLEAR';
  }
}

/** For tests: flush the cached linguist data so the next call reloads from disk. */
export function __resetCache(): void {
  cached = null;
}
